In [22]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

In [23]:
data=pd.read_csv('/content/sample_data/car_evaluation.csv',names=['buying price','maintainance cost','no.of doors','no.of persons','lugboot','safety','unaccurate'])

In [24]:
data

,buying price,maintainance cost,no.of doors,no.of persons,lugboot,safety,unaccurate
0,vhigh,vhigh,2,2,small,low,unacc
1,vhigh,vhigh,2,2,small,med,unacc
2,vhigh,vhigh,2,2,small,high,unacc
3,vhigh,vhigh,2,2,med,low,unacc
4,vhigh,vhigh,2,2,med,med,unacc
...,...,...,...,...,...,...,...
1723,low,low,5more,more,med,med,good
1724,low,low,5more,more,med,high,vgood
1725,low,low,5more,more,big,low,unacc
1726,low,low,5more,more,big,med,good
1727,low,low,5more,more,big,high,vgood

In [26]:
X=data.drop('unaccurate',axis=1)

X

     buying price maintainance cost no.of doors no.of persons lugboot safety
0           vhigh             vhigh           2             2   small    low
1           vhigh             vhigh           2             2   small    med
2           vhigh             vhigh           2             2   small   high
3           vhigh             vhigh           2             2     med    low
4           vhigh             vhigh           2             2     med    med
...           ...               ...         ...           ...     ...    ...
1723          low               low       5more          more     med    med
1724          low               low       5more          more     med   high
1725          low               low       5more          more     big    low
1726          low               low       5more          more     big    med
1727          low               low       5more          more     big   high

[1728 rows x 6 columns]

In [31]:
y=data['unaccurate']
y

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...
1723     good
1724    vgood
1725    unacc
1726     good
1727    vgood
Name: unaccurate, Length: 1728, dtype: object

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, y_train, X_test, y_test= train_test_split(X,y,test_size=0.3,random_state=50)

In [34]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()

In [36]:
clf.fit(X_train,y_train)

ValueError: ignored

In [ ]:
y_pred=clf.predict(X_test)

In [ ]:
print("accuracy:",accuracy_score(y_test,y_pred)
)

In [18]:
from sklearn.tree import export_graphviz
import pydotplus
from six import StringIO
from IPython.display import Image

In [ ]:
dot_data=StringIO()
export_graphviz(clf,out_file=dot_data,filled=True,rounded=True,special_characters=True,features_name=data.feature_name,class_name=data.target_name)
graph=pydotplus.graph_from_dot_data(dot_data.get_value())
Image(graph.create_png())